[project]
name = "advance-regression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sumant1708", email = "sumantdas170803@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
advance-regression = "advance_regression:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
